//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobAlytaloMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saunat
    {
        public int SaunaID { get; set; }
        public string SaunaNimi { get; set; }
        public bool SaunanTila { get; set; }
        public int SaunanNykyLampotila { get; set; }
    }
}
