//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobAlytaloMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termostaatti
    {
        public int TermostaattiID { get; set; }
        public string TermostaattiNimi { get; set; }
        public bool TermostaattiTila { get; set; }
        public int TermostaattiNykyLampo { get; set; }
    }
}
