//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobAlytaloMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valot
    {
        public int ValoID { get; set; }
        public string HuoneValo { get; set; }
        public bool ValoOff { get; set; }
        public bool Valo33 { get; set; }
        public bool Valo66 { get; set; }
        public bool Valo100 { get; set; }
    }
}
